[project]
name = "linkedin_automation"
version = "0.1.0"
description = "Automation tools for LinkedIn tasks."
authors = ["Your Name <your.email@example.com>"]

[tool.setuptools]
packages = ["src.linkedin_automation"]
