name: Daily LinkedIn Post

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:        # allow manual trigger too

jobs:
  run-bot:
    runs-on: macos-latest   # Safari WebDriver only works on macOS!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LinkedIn bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: |
          python src/linkedin_automation/main.py
